### PR TITLE
Refactored to reduce code repetition

### PR DESCRIPTION
**Pull request by cam-barts**
Instead of all of the print statements, I refactored to use menu objects so everything comes out clean and consistent. 

Took out webbrowser from requirements, because it is a part of the standard lib and doesn't need to be downloaded externally. 

Optimized for extendability.

### CODE REVIEW

**Comment by jakecreps** [comment]
Thanks for this addition! I'm actually quite new to Python and much of the additions you've created are a bit above my head. For the time being, I will leave it as is.  I'll review your code later after I've gotten closer to completing the project for simplification.

**Comment by cam-barts** [comment]
Thanks for the feedback! I would be happy to go through my changes and write out comments to explain what the code is doing. Not writing comments is one of my worst habits, so it would help be get better too.  Most of the work is just putting the repetitive blocks into functions so you don't have to write so much.

**Comment by cam-barts** [comment]
I fixed merge conflicts and added a bunch of doc strings and comments to try and make what I was doing clearer. I really enjoy this project and hope this work is helpful.

**Comment by jakecreps** [comment]
Thanks for your work! I'll look everything over and see if I have any questions.

**Comment by jakecreps** [comment]
So there are some issues with your code that I've identified.  Unfortunately I've merged and I'm not super savvy on how to undo that.  Your code doesn't loop through the menus allowing users to select multiple tools.  Also, the spacing on the UI is off too.

**Comment by cam-barts** [comment]
Those are easy fixes. With the spacing issue, I can just fix the `menu_option` function in utils instead of having to go through each statement, which was the point in refactoring. I just need some clarification as to what you mean by it being "off". As far as looping through the menus, I can fix that in another pull as well.

**Comment by jakecreps** [comment]
By "off" I mean that there should be a space between each input.  If you refer to the original code, you will see what I mean. For example

Select a directory:

Select a directory:

Instead of 

Select a directory:
Select a directory:

**Comment by cam-barts** [comment]
I never actually got that, it acted buggy. I am on a windows machine and got 
```
?[33m Select: ?[37m1  # selected 1
?[33m Select: ?[37m
```
Would you be opposed to showing the entire menu with each selection? I'll open a pull and see how you like it.

**Pull request merged**
